name: Build AURA APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip Project
        run: |
          ZIPFILE=$(ls *.zip AURA* 2>/dev/null | head -n 1)
          echo "Found $ZIPFILE"
          if [ -n "$ZIPFILE" ]; then
            unzip -o "$ZIPFILE"
            rm -f "$ZIPFILE"
          fi
          if [ -d "AURA_FIREBASE_GITHUB_FINAL" ]; then
            shopt -s dotglob
            cp -r AURA_FIREBASE_GITHUB_FINAL/*. || true
            rm -rf AURA_FIREBASE_GITHUB_FINAL
          fi
          ls -la
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build APK
        run:./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AURA-Music-APK
          path: app/build/outputs/apk/debug/app-debug.apk
